spring.application.name=DevPrep
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${DB_URL}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


#Application logs
logging.file.name=logs/devprep.log
logging.level.com.devprep.devprepai=INFO

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE