spring.application.name=DevPrep
spring.datasource.username=root
spring.datasource.password=Abhi@123
spring.datasource.url=jdbc:mysql://localhost:3306/devprep
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


jwt.secret=${JWT_SECRET:devprep-authentication-secret-key-change-this-in-production-2026}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}


#Application logs
logging.file.name=logs/devprep.log
logging.level.com.devprep.devprepai=INFO

logging.level.org.springframework=OFF
logging.level.org.hibernate=OFF
logging.level.org.apache=OFF
logging.level.com.zaxxer.hikari=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm=OFF
logging.level.org.springframework.security=WARN
